# Generated by Django 4.0.7 on 2023-12-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='outsourceesregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('companyemailid', models.EmailField(max_length=254, unique=True)),
                ('contactperson', models.CharField(max_length=20)),
                ('phoneno', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('approve', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('login', models.BooleanField(default=False)),
                ('logout', models.BooleanField(default=True)),
            ],
        ),
    ]
