# Generated by Django 4.0.7 on 2023-12-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcees', '0002_outsourceesregistration_ntime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsourceesregistration',
            name='Ntime',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
