# Generated by Django 4.0.7 on 2023-12-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZKPprotocols', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SPregistration',
            new_name='zkpregistration',
        ),
    ]
