# Generated by Django 4.0.7 on 2023-12-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0005_spregistration_contract_spregistration_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spregistration',
            name='request',
            field=models.BooleanField(default=False),
        ),
    ]
