# Generated by Django 4.0.7 on 2023-12-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0008_spregistration_companyemailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spregistration',
            name='industry',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
