# Generated by Django 4.0.7 on 2023-12-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0010_spregistration_contractlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='sendntimeoutsourcees',
            field=models.BooleanField(default=False),
        ),
    ]
