# Generated by Django 4.0.7 on 2023-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0012_spregistration_zkpprotocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='Outscomply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spregistration',
            name='spcomply',
            field=models.BooleanField(default=False),
        ),
    ]
