# Generated by Django 4.0.7 on 2023-12-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0013_spregistration_outscomply_spregistration_spcomply'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='contractapprov',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spregistration',
            name='contractreject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spregistration',
            name='zkpadminapprove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spregistration',
            name='zkpadminreject',
            field=models.BooleanField(default=False),
        ),
    ]
