# Generated by Django 4.0.7 on 2023-12-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0014_spregistration_contractapprov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='zkpidentifier',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
