# Generated by Django 4.0.7 on 2023-12-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0015_spregistration_zkpidentifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='fileupload1',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
