# Generated by Django 4.0.7 on 2023-12-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0016_spregistration_fileupload1'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='leakdata',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
