# Generated by Django 4.0.7 on 2023-12-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0017_spregistration_leakdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='sendtooutsoucees',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
