# Generated by Django 4.0.7 on 2023-12-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0019_spregistration_complaint_spregistration_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='leakcontent',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
