# Generated by Django 4.0.7 on 2023-12-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0021_spregistration_sendsolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spregistration',
            name='complaint',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
