# Generated by Django 4.0.7 on 2023-12-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0022_alter_spregistration_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='inspect',
            field=models.BooleanField(default=False),
        ),
    ]
