# Generated by Django 4.0.7 on 2023-12-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0023_spregistration_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spregistration',
            name='complaint',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
