# Generated by Django 4.0.7 on 2024-03-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0024_alter_spregistration_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='key',
            field=models.BinaryField(max_length=20, null=True),
        ),
    ]
