# Generated by Django 4.0.7 on 2024-03-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceproviders', '0025_spregistration_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='spregistration',
            name='spid',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='spregistration',
            name='key',
            field=models.BinaryField(max_length=100, null=True),
        ),
    ]
