# Generated by Django 4.0.7 on 2023-12-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('companyemailid', models.EmailField(max_length=254, unique=True)),
                ('contactperson', models.CharField(max_length=20)),
                ('phoneno', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('approve', models.BooleanField(default=False)),
                ('reject', models.BooleanField(default=False)),
                ('login', models.BooleanField(default=False)),
                ('logout', models.BooleanField(default=True)),
                ('process', models.BooleanField(default=False)),
                ('upload', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='comprequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('contactperson', models.CharField(max_length=20)),
                ('companyemailid', models.EmailField(max_length=254, null=True, unique=True)),
                ('location', models.CharField(max_length=10)),
                ('industry', models.CharField(max_length=20, null=True)),
                ('serviceneed', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('budget', models.CharField(max_length=20, null=True)),
                ('accept', models.BooleanField(default=False)),
                ('request', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='myresource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20, null=True)),
                ('contactperson', models.CharField(max_length=20, null=True)),
                ('companyemailid', models.EmailField(max_length=254, null=True, unique=True)),
                ('fileupload1', models.FileField(upload_to='documents/')),
                ('FullName', models.CharField(max_length=20, null=True)),
                ('DateofBirth', models.CharField(max_length=20, null=True)),
                ('Gender', models.EmailField(max_length=254, null=True, unique=True)),
                ('Address', models.CharField(max_length=10, null=True)),
                ('Phone', models.CharField(max_length=20, null=True)),
                ('Insurance', models.CharField(max_length=200, null=True)),
                ('DiagnosisName', models.CharField(max_length=20, null=True)),
                ('ProcedureName', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
