# Generated by Django 4.0.7 on 2023-12-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcingportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprequirement',
            name='fileupload1',
            field=models.FileField(default=None, upload_to='documents/'),
        ),
    ]
