# Generated by Django 4.0.7 on 2024-04-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcingportal', '0003_alter_compregistration_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprequirement',
            name='companyemailid',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
